name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile --windowed main.py

      - name: Prepare Files
        run: Compress-Archive -Path dist\main.exe -DestinationPath ocrmypdf-ui-windows.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ocrmypdf-ui-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}